### ISSUE TITLE
Spline Grading Function

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#155]
## What
Instead of scoring 0 - 99, we apply a spline-like curve and grading function 

## Why
We believe this will lead to a better distribution of points - lower points will be more extended into the middle, higher points remain unchanged (still linear)\

## Spec
Map 0-99 in the scores to the 0-99 as defined by the appended Excel sheet

Since the calculation is a bit complicated, might be easier to just have a table mapping 0-99 ->0-99

Or a hard-coded vector with the mapping in it. It's only 100 values and an array will be the most efficient way to handle this during our calculations.

**Comment by n13** [comment]
[Spline_Example2.xlsx](https://github.com/JoinSEEDS/seeds-smart-contracts/files/5523959/Spline_Example2.xlsx)

**Comment by IanMendozaJaimes** [comment]
Hello I have some questions:
- I think I don't understand what the spline-like curve is replacing, could you spec a little bit more what do you mean by "scoring 0-99"? Will users will be still ranked from 0 to 99 and then score them?, do you mean to use the spline-like curve instead of the 0-2 conversion?
- The values in the table that should be mapped are index -> SplineVal(0-99), right? (from excel)

**Comment by juliolrmonteiro** [comment]
Every rank should use spline, except for composite scores (like contribution scores for orgs or individuals).
No doubling up calculation.
