### ISSUE TITLE
Unified QEV Calculation

### ISSUE THREAD

**Issue by juliolrmonteiro** [JoinSEEDS/seeds-smart-contracts#167]
Have a single transactions history table stored in a daily scope

So here's a completely new idea on how to do all our transaction point and QEV calculations in one table

The key differences to the old system are:
- daily tables and daily summaries
- limit of 2 per day for transactions between the same accounts (replaces 26 per month)
- Everything is clocked daily and stored in a table scoped by day (in UTC 00:00)

[Google sheet with new table structure](https://docs.google.com/spreadsheets/d/1-Q6bkm7qFXwoden_P7pQV6QM5XY8afrLADS_aqaG9bo/edit?usp=sharing)

|ID                                         |From|To                         |Volume|Qualifying Volume|FromPoints|ToPoints|Time|
|-------------------------------------------|----|---------------------------|------|-----------------|----------|--------|----|
|0                                          |a   |b                          |30    |30               |30        |5       |....|
|1                                          |a   |b                          |200   |200              |60        |10      |....|
|3                                          |c   |d                          |60,000|1777             |40        |33      |....|
|4                                          |a   |b                          |400   |0                |0         |0       |....|

Transaction comes in, is added to the list - checks whether or not it's more than 2 between 2 accounts and does the calculation for qualifying vol, from points, to points

If there's already 2 transactions and this is the 3rd, it's not added to the list - simplification we don't take the 2 highest volume transactions, we just take the first 2

[2] is a parameter

As a transaction comes in we 
- generate the scope from the timestamp
- save it to the table
- place a delayed transaction with the id

#### The delayed transaction (id, timestamp)
calculates from points, to points, QEV - this all depends on reputation scores / individual vs. org (only orgs get points as the receover and so on. and enters these points into tables for individual tx points, org tx points, and QEV

These are daily tables that accumulate a day with the timestamp, scoped by name

So each user has a 120 day trailing table of time stamped tx points - their total tx points can then be easily calculated by just adding them up

scope user

|Timestamp UTC 00:00  |points|
|------------------------|------|
|0                                       |3  
|1                                       |24  

QEV
|Timestamp UTC 00:00  |Qualifying volume|
|------------------------|------------------|
|0                                      |220
|1                                       |701  

## tx score for orgs
Just like we do now transaction score for orgs is calculated in harvest, but it can just add up all the points in the account's table

## tx score for individuals
same as for orgs - the calculation can run as usual, but it will just sum up the last X days

## QEV
similar to tx scores, QEV can be calculated based on the daily QEV data - so we calculate 30 day trailing QEV and 90-120 day trailing QEV to compare them

## Timestamps
Ian already wrote a utility for this, we can use this for all timestamps here
```
uint64_t harvest::get_beginning_of_day_in_seconds() {
   auto sec = eosio::current_time_point().sec_since_epoch();
   auto date = eosio::time_point_sec(sec / 86400 * 86400);
   return date.utc_seconds;
 }
```

**Comment by n13** [comment]
@Rieki7 please review
@IanMendozaJaimes alsp please let me know if this makes sense, and is better than what we orgiinally planned.

I know we already spent some time on implementing it the old way, but it's more important to have the best implementation

**Comment by Rieki7** [comment]
Question... Is it just as easy to have a new transaction come in - check to see if its *larger* than the existing 2 and replace it (this way we are still taking the highest two) if its at all complicated to do that.. .Then lets not worry

**Comment by Rieki7** [comment]
This all looks perfect! I assume its here - but if not... Are we also keeping track of the total volume per account? This can be in one place and just ticks up each time...

**Comment by n13** [comment]
> Question... Is it just as easy to have a new transaction come in - check to see if its _larger_ than the existing 2 and replace it (this way we are still taking the highest two) if its at all complicated to do that.. .Then lets not worry

That should work just fine

**Comment by n13** [comment]
> This all looks perfect! I assume its here - but if not... Are we also keeping track of the total volume per account? This can be in one place and just ticks up each time...

We can yes - do we need to keep track of total volume per account? I guess it was for orgs... we can definitely add that easily.

**Comment by IanMendozaJaimes** [comment]
Hello, I think this way looks much better, but I have some questions:
> Have a single transactions history table stored in a daily scope

- Is this a replacement for tables `org_tx_table` and `transaction_tables`?

- Is `ToPoints` needed to calculate orgs transaction score? if so, does it mean if a user receives a transaction `ToPoints` will be zero?

> If there's already 2 transactions and this is the 3rd, it's not added to the list

- A user is still allowed to make more than 2 transactions per day, right?, does this mean that the 3rd transaction does not count at all for the user's transaction score?. Also, in the example there are three transactions from user a to user b, but below you said that we don't add the third transaction to the list, by that, did you mean to store the transaction record in the new table scoped by timestamp but not store anything in the daily tables?

- Just to make sure, this tuple (from: userA, to: userB, 10.0000 SEEDS) is the same as (from: userB, to: userA, 10.0000 SEEDS), because userA and userB are exchanging exactly the same amount of Seeds, right? So the transaction is recorded in the table scoped by timestamp, but `FromPoints` and `ToPoints` are zero for the second transaction (userB, userA, 10.0000 SEEDS)?

> These are daily tables that accumulate a day with the timestamp, scoped by name
- Those are different tables than the ones used to rank orgs and users, right? The total sum of these new tables is stored in the tables used to rank users and orgs

- About the transaction score, I noticed it will be static now. I mean, the volume * user's reputation won't change as the result is stored in a table, so even the user's reputation changes, the points the user received for that transaction don't change. As the total score will be the sum of all the transactions entries in the case of orgs, is it ok to just have a total value stored? in that way, the total transaction score for an org will be calculated as soon as the org receives or make a transaction

> So each user has a 120 day trailing table of time stamped tx points

- Should all transactions (stored in the daily tables) older than 120 days be deleted?

- About having the two highest volume transactions, I think it's easy to implement it, but can you please confirm me which one I should do?, the option where we keep the first 2 transactions or the option where we keep the 2 highest

- Should I add the total volume per account?

**Comment by n13** [comment]
> Hello, I think this way looks much better, but I have some questions:
> 
> > Have a single transactions history table stored in a daily scope
> 
> * Is this a replacement for tables `org_tx_table` and `transaction_tables`?

Yes

> * Is `ToPoints` needed to calculate orgs transaction score? if so, does it mean if a user receives a transaction `ToPoints` will be zero?

Exactly - that was my thinking. It's there only for orgs. 

> 
> > If there's already 2 transactions and this is the 3rd, it's not added to the list
> 
> * A user is still allowed to make more than 2 transactions per day, right?, does this mean that the 3rd transaction does not count at all for the user's transaction score?. Also, in the example there are three transactions from user a to user b, but below you said that we don't add the third transaction to the list, by that, did you mean to store the transaction record in the new table scoped by timestamp but not store anything in the daily tables?

Yes we were debating between - adding the 3rd transaction and just not counting it later, or not adding the 3rd transaction

I think not adding the 3rd transaction is better. 

Rieki suggested we keep 2, and if a 3rd one comes in we replace one of the 2 IF the 3rd one is bigger than one of the two- that way we would still have the daily top 2. 

Depending on how and when we do the scoring, this may be good.

As for doing scoring immediately as transactions come in - we should do that in a delayed transaction because I don't want failed transactions due to timeouts. We already have to check if the users exist though - and in this check, maybe just pulling user data such as reputation score is not any more expensive? I am not sure.

I have some concerns about how much we can do before we become unreliable with our transactions. 

And yes, users can make as many transactions as they want, this is only about scoring and what to include in the score.

> * Just to make sure, this tuple (from: userA, to: userB, 10.0000 SEEDS) is the same as (from: userB, to: userA, 10.0000 SEEDS), because userA and userB are exchanging exactly the same amount of Seeds, right? So the transaction is recorded in the table scoped by timestamp, but `FromPoints` and `ToPoints` are zero for the second transaction (userB, userA, 10.0000 SEEDS)?
> 


Hmm I don't quite understand but let me do it from my perspective

The first one userA to userB, userA would get points depending on the reputation score of user B. userB is an individual and would not get points for this incoming transaction

The second one userB to userA, userB would get points depending on the reputation score of user A, userA is an individual and would get 0 points (no points for incoming). 

If one of them were an org, they would get points for incoming, depending on the reputation score of the sender. 

Does that clarity? I don't quite understand the question so please clarify. Thanks.

> > These are daily tables that accumulate a day with the timestamp, scoped by name
> 
> * Those are different tables than the ones used to rank orgs and users, right? The total sum of these new tables is stored in the tables used to rank users and orgs

Yes they're different. Instead of keeping all transactions for 3 cycles trailing, we instead keep a daily value for each account trailing 3 or 4 cycles. 

So each account has a table like that (timestamp, daily_tx_points) and we use this table to figure out the account's current total transaction points and later rank.


> * About the transaction score, I noticed it will be static now. I mean, the volume * user's reputation won't change as the result is stored in a table, so even the user's reputation changes, the points the user received for that transaction don't change. As the total score will be the sum of all the transactions entries in the case of orgs, is it ok to just have a total value stored? in that way, the total transaction score for an org will be calculated as soon as the org receives or make a transaction

That's correct. It is less dynamic. I guess that's OK - @Rieki7 ?

> 
> > So each user has a 120 day trailing table of time stamped tx points
> 
> * Should all transactions (stored in the daily tables) older than 120 days be deleted?

each daily master table can be deleted as soon as it's processed - meaning all its data has been consumed

the master table gets distributed as daily tx points to accounts and orgs, and as daily QEV to the qev table. 


> * About having the two highest volume transactions, I think it's easy to implement it, but can you please confirm me which one I should do?, the option where we keep the first 2 transactions or the option where we keep the 2 highest

keep the 2 highest definitely preferred.

> * Should I add the total volume per account?

Yes!!
