### ISSUE TITLE
Change: Quorum based on "actives" instead of demoting citizens

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#187]
I know we just got the code done to demote inactive citizens

But demoting citizens is not a nice thing to do, so we decided it's better to just base the quorum on active users, and leave citizens be citizens even if they don't vote.

I think we already have an actives list but not enturely sure how it works.

In any case we keep a list of actives like this

- When someone votes, they are added to the actives list, and a timestamp of the vote set. If they're already in the list, the timestamp is updated. 
- At each cycle, we run through the actives list and remove all citizens that have not voted for 3 cycles or more
- At each cycle, we run through the actives list, and count everyone's vote power - or we can count the vote power as we distribute new votes, but the vote power is only added when someone is in the actives list. 
This could also be a separate action that runs after votes have been distributed. - however it's easiest to implement.

The point is, we then have the total vote power for a round which is 

SUM(active users' vote points)

We can then use the sum of the vote points as a quorum

Quorum is then

(votes for) as a % of total vote points > quorum %

## Addendum 1

If someone who is not active suddenly starts voting, then they are entered into the actives table, and their score, prior to the vote, is added to the quorum total.

So let's say user A is inactive and has 45 points. Not in actives list, and so they were not counted for the total vote power of the round.

But then they jump in and vote 15 points on proposal 217

We determine that they're not in the actives table yes, and we add their 45 points to the total. 

## Addendum 2
Active table will also have to be done for delegate votes meaning a user who delegated their vote, gets refreshed in the actives table whenever their delegatee votes.

**Comment by juliolrmonteiro** [comment]
@n13 Question here: if we allow inactive citizens to jump in and vote changing the quorum, this could lead to proposals that were near to pass or to fail, to change abruptly on last minute, no?

**Comment by markflowfarm** [comment]
I believe the Quorum requirement should be nailed down at the beginning of the voting cycle, and it should not change during the cycle.  So, the Quorum requirement for each Category is then [ Sum(Actives) * 0.9 / #ProposalsInCategory ].
{Is that still the formula?}

So... everyone is distributed their Voting tokens each cycle (regardless of Active or Inactive), but the Quorum computation ignores those that haven't voted in most recent three cycles.  Right?

Wondering if you need to take care to include Citizen who have recently evolved, but haven't yet voted.  In some sense they should be considered Active (they are just new), but it's probably ok to think of them as Inactive (since they've never voted).  I could go either way on this point.

With this suggestion, then if people decide to start voting that we're previously Inactive, then they will help to get to Quorum easier.  I see nothing wrong with that.  Comments?
