### ISSUE TITLE
Claim back unused invites

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#328]
We will send unused invites back to the user after 2 weeks. 

Saves memory on the contracts and cleans up the clutter

## Spec

- Scheduler calls into join.seeds "chkcleanup"

- Join.seeds has a new table called timestamp_table and a function cleanup(from_id, to_id) that cleans unclaimed invites between 2 indices. (already implemented)

timestamp table has
id
invite_id
timestamp

invite_id is the most recent invite id currently in the invites table
timestamp is the current time

chkcleanup does the following
check if timestamp table is empty - 

if not empty, initiate a cleanup action on all IDs lower than that ID

whether or not it's empty, add a new entry to the timestamp table with the current last invite ID, and the current timestamp

have some safety check that timestamp isn't < 3 days old? or enforce setting time interval between cleanups? 

One of these 2 - we normally do not trust the scheduler to be accurate with their calls, so should enforce the interval here, and the scheduler can then run every day.

**Comment by juliolrmonteiro** [comment]
Just add this to the scheduler, right? @n13

**Comment by IanMendozaJaimes** [comment]
Hello @n13, I have some questions:
- I got a little bit confused about this line:
 > have some safety check that timestamp isn't < 3 days old? or enforce setting time interval between cleanups?

Because in the issue description you say that this will erase the unused invites every 2 weeks, so just to clarify are both checks kind of the same? I mean I just need to verify the last `invite_id` in the timestamp table is older than [14] days to start the cleanup method?

- Also, should the 2 weeks be a parameter?

**Comment by n13** [comment]
- don't need to be a parameter for now
- I wanted an additional safety check in case the scheduler misfires.
