### ISSUE TITLE
dao.seeds needs to easily allow voice scopes being added or removed

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#395]
## Use case
- We add a new category of proposal called "cats"
- users receive voice scopes for cats
- voting happens on that scope

## Use case 2
- we remove category cats again - that prop type no longer exists
- voice scopes for cats are removed

Just want to make sure that this is easily possible.

**Comment by IanMendozaJaimes** [comment]
@n13 hello, in the dao.seeds contract the voice scopes are defined in the contract as constants. 

There is a vector of scopes, the functions: `updatevoice`, `decayvoice`, `delegate`, `undelegate`, `changetrust` and in general all the voice methods use that vector of voice scopes, so we would only have to add "cats" to that vector and it will work as the rest of scopes.

I am not quite sure a table is needed in this case (instead of a vector in the contract), I mean a table would allow you to add scopes without having to recompile the contract, but adding a new proposal type would require to recompile the contract anyways.

In the case of removal, it would be the same.

The problem is that for both cases, the changes will take effect in the next cycle, or better saying, they will take effect the next time `updatevoice`is called:
- for adding a scope, `updatevoice` will create it
- for removing it, `updatevoice` won't update it anymore but currently it won't explicitly remove it from the users

So I think another action to delete a scope from the voice table for all the users has to be added to ensure the old scope being removed completely.

**Comment by IanMendozaJaimes** [comment]
Hello @n13, I just need some confirmation:
- Would you like the vector of scopes change for a table?
- When you add the scope "cats", is it ok if the contract gives the scope to the users in the next period? or better to see the change immediately
- I would need to add another function to erase the remaining of the erased voice scope, is that ok?
