### ISSUE TITLE
Transaction Limit By Planted Seeds

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#51]
## Limit transactions by planted

[1] planted seed = N tx / day where [N] is a setting

N = 10 initially, so we get 10 tx / day / planted seed

Implement this for 2x for now compared to constitution - we want to prevent abuse of the system, but we also want to prevent users running into this.

Larger of 7 / week OR 2x planted value.

## Implementation hints

- Minimum 1 / day (0 planted)
- We reset the transactions weekly
- incremental reset with delayed transactions so reset doesn't fail
- Only affects individuals, no check for organizations or bioregions
- look into using existing function check_limit 
- add resetweekly in token contract to scheduler so it's called every day 
- add new setting

<img width="549" alt="image" src="https://user-images.githubusercontent.com/65412/81511879-cb748580-931c-11ea-9f9d-53ea799e24d2.png">

**Comment by IanMendozaJaimes** [comment]
1. I see check_limit is commented, is this issue replacing the check_limit's functionality?
2. Which quantity are you referring to by 2x compared to constitution? Is it the planted value?, in that case, is the planted value the amount of planted seeds?
3. Sorry but I think I don't understand what you mean by this line: Larger of 7 / week OR 2x planted value.
4. If we configure the resetweekly function to be called daily, isn't going to reach a point where transactions will be reset daily instead of weekly? 
5. The resetweekly function does not handle batches, do I have to implement this incremental reset as well right?

**Comment by n13** [comment]
# Deployment

## Testnet

- [ ] token
- [ ] scheduler


## Mainnet 

- [ ] token
- [ ] scheduler

**Comment by n13** [comment]
deployd

**Comment by n13** [comment]
Deployed
